AWSTemplateFormatVersion: '2010-09-09'
Description: 'EventBridge Rules for Customer Engagement & Action Platform (CEAP)'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name for resource naming

  ProjectName:
    Type: String
    Default: ceap-platform
    Description: Project name for resource naming

  BatchIngestionStateMachineArn:
    Type: String
    Description: ARN of the Batch Ingestion Step Functions State Machine

  ReactiveCeapStateMachineArn:
    Type: String
    Description: ARN of the Reactive CEAP Step Functions State Machine

Resources:
  # ============================================================================
  # IAM Role for EventBridge to invoke Step Functions
  # ============================================================================

  EventBridgeStepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-eventbridge-stepfunctions-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeStepFunctionsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource:
                  - !Ref BatchIngestionStateMachineArn
                  - !Ref ReactiveCeapStateMachineArn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # ============================================================================
  # Scheduled Rules for Batch Ingestion
  # ============================================================================

  # Daily batch ingestion for retail program
  RetailBatchScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ProjectName}-retail-batch-schedule-${Environment}'
      Description: 'Daily batch ingestion for retail ceap program'
      ScheduleExpression: 'cron(0 2 * * ? *)'  # 2 AM UTC daily
      State: ENABLED
      Targets:
        - Arn: !Ref BatchIngestionStateMachineArn
          RoleArn: !GetAtt EventBridgeStepFunctionsRole.Arn
          Id: RetailBatchTarget
          Input: !Sub |
            {
              "programId": "retail",
              "marketplace": "US",
              "batchId": "retail-<aws.events.rule-name>-<aws.events.event.ingestion-time>",
              "correlationId": "<aws.events.event.id>"
            }
          RetryPolicy:
            MaximumRetryAttempts: 2
            MaximumEventAge: 3600

  # Weekly batch ingestion for subscription program
  SubscriptionBatchScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ProjectName}-subscription-batch-schedule-${Environment}'
      Description: 'Weekly batch ingestion for subscription ceap program'
      ScheduleExpression: 'cron(0 3 ? * MON *)'  # 3 AM UTC every Monday
      State: ENABLED
      Targets:
        - Arn: !Ref BatchIngestionStateMachineArn
          RoleArn: !GetAtt EventBridgeStepFunctionsRole.Arn
          Id: SubscriptionBatchTarget
          Input: !Sub |
            {
              "programId": "subscription",
              "marketplace": "US",
              "batchId": "subscription-<aws.events.rule-name>-<aws.events.event.ingestion-time>",
              "correlationId": "<aws.events.event.id>"
            }
          RetryPolicy:
            MaximumRetryAttempts: 2
            MaximumEventAge: 3600

  # Hourly batch ingestion for high-frequency program
  HighFrequencyBatchScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ProjectName}-highfreq-batch-schedule-${Environment}'
      Description: 'Hourly batch ingestion for high-frequency ceap program'
      ScheduleExpression: 'rate(1 hour)'
      State: ENABLED
      Targets:
        - Arn: !Ref BatchIngestionStateMachineArn
          RoleArn: !GetAtt EventBridgeStepFunctionsRole.Arn
          Id: HighFreqBatchTarget
          Input: !Sub |
            {
              "programId": "high-frequency",
              "marketplace": "US",
              "batchId": "highfreq-<aws.events.rule-name>-<aws.events.event.ingestion-time>",
              "correlationId": "<aws.events.event.id>"
            }
          RetryPolicy:
            MaximumRetryAttempts: 2
            MaximumEventAge: 3600

  # ============================================================================
  # Event Patterns for Reactive CEAP
  # ============================================================================

  # Customer order placed event
  CustomerOrderPlacedRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ProjectName}-customer-order-placed-${Environment}'
      Description: 'Trigger reactive ceap when customer places an order'
      EventPattern:
        source:
          - com.amazon.orders
        detail-type:
          - Order Placed
        detail:
          orderStatus:
            - CONFIRMED
      State: ENABLED
      Targets:
        - Arn: !Ref ReactiveCeapStateMachineArn
          RoleArn: !GetAtt EventBridgeStepFunctionsRole.Arn
          Id: OrderPlacedTarget
          InputTransformer:
            InputPathsMap:
              customerId: $.detail.customerId
              orderId: $.detail.orderId
              marketplace: $.detail.marketplace
              eventId: $.id
              eventTime: $.time
            InputTemplate: |
              {
                "programId": "post-purchase",
                "marketplace": <marketplace>,
                "eventType": "ORDER_PLACED",
                "correlationId": <eventId>,
                "candidates": [
                  {
                    "customerId": <customerId>,
                    "subject": {
                      "type": "ORDER",
                      "id": <orderId>
                    },
                    "context": [
                      {
                        "key": "eventTime",
                        "value": <eventTime>
                      }
                    ]
                  }
                ]
              }
          RetryPolicy:
            MaximumRetryAttempts: 2
            MaximumEventAge: 300

  # Customer subscription renewal event
  SubscriptionRenewalRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ProjectName}-subscription-renewal-${Environment}'
      Description: 'Trigger reactive ceap for subscription renewals'
      EventPattern:
        source:
          - com.amazon.subscriptions
        detail-type:
          - Subscription Renewal
        detail:
          renewalStatus:
            - UPCOMING
            - FAILED
      State: ENABLED
      Targets:
        - Arn: !Ref ReactiveCeapStateMachineArn
          RoleArn: !GetAtt EventBridgeStepFunctionsRole.Arn
          Id: SubscriptionRenewalTarget
          InputTransformer:
            InputPathsMap:
              customerId: $.detail.customerId
              subscriptionId: $.detail.subscriptionId
              marketplace: $.detail.marketplace
              renewalStatus: $.detail.renewalStatus
              eventId: $.id
            InputTemplate: |
              {
                "programId": "subscription-retention",
                "marketplace": <marketplace>,
                "eventType": "SUBSCRIPTION_RENEWAL",
                "correlationId": <eventId>,
                "candidates": [
                  {
                    "customerId": <customerId>,
                    "subject": {
                      "type": "SUBSCRIPTION",
                      "id": <subscriptionId>
                    },
                    "context": [
                      {
                        "key": "renewalStatus",
                        "value": <renewalStatus>
                      }
                    ]
                  }
                ]
              }
          RetryPolicy:
            MaximumRetryAttempts: 2
            MaximumEventAge: 300

  # Customer product view event
  ProductViewRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ProjectName}-product-view-${Environment}'
      Description: 'Trigger reactive ceap for high-value product views'
      EventPattern:
        source:
          - com.amazon.catalog
        detail-type:
          - Product View
        detail:
          productCategory:
            - Electronics
            - Computers
          viewDuration:
            - numeric:
                - '>='
                - 30
      State: ENABLED
      Targets:
        - Arn: !Ref ReactiveCeapStateMachineArn
          RoleArn: !GetAtt EventBridgeStepFunctionsRole.Arn
          Id: ProductViewTarget
          InputTransformer:
            InputPathsMap:
              customerId: $.detail.customerId
              productId: $.detail.productId
              marketplace: $.detail.marketplace
              category: $.detail.productCategory
              eventId: $.id
            InputTemplate: |
              {
                "programId": "browse-engagement",
                "marketplace": <marketplace>,
                "eventType": "PRODUCT_VIEW",
                "correlationId": <eventId>,
                "candidates": [
                  {
                    "customerId": <customerId>,
                    "subject": {
                      "type": "PRODUCT",
                      "id": <productId>
                    },
                    "context": [
                      {
                        "key": "category",
                        "value": <category>
                      }
                    ]
                  }
                ]
              }
          RetryPolicy:
            MaximumRetryAttempts: 2
            MaximumEventAge: 300

  # Customer cart abandonment event
  CartAbandonmentRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ProjectName}-cart-abandonment-${Environment}'
      Description: 'Trigger reactive ceap for cart abandonment'
      EventPattern:
        source:
          - com.amazon.cart
        detail-type:
          - Cart Abandoned
        detail:
          cartValue:
            - numeric:
                - '>='
                - 50
      State: ENABLED
      Targets:
        - Arn: !Ref ReactiveCeapStateMachineArn
          RoleArn: !GetAtt EventBridgeStepFunctionsRole.Arn
          Id: CartAbandonmentTarget
          InputTransformer:
            InputPathsMap:
              customerId: $.detail.customerId
              cartId: $.detail.cartId
              marketplace: $.detail.marketplace
              cartValue: $.detail.cartValue
              eventId: $.id
            InputTemplate: |
              {
                "programId": "cart-recovery",
                "marketplace": <marketplace>,
                "eventType": "CART_ABANDONED",
                "correlationId": <eventId>,
                "candidates": [
                  {
                    "customerId": <customerId>,
                    "subject": {
                      "type": "CART",
                      "id": <cartId>
                    },
                    "context": [
                      {
                        "key": "cartValue",
                        "value": <cartValue>
                      }
                    ]
                  }
                ]
              }
          RetryPolicy:
            MaximumRetryAttempts: 2
            MaximumEventAge: 300

  # ============================================================================
  # CloudWatch Alarms for Rule Failures
  # ============================================================================

  BatchIngestionFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-batch-ingestion-failures-${Environment}'
      AlarmDescription: 'Alert when batch ingestion rules fail to trigger'
      MetricName: FailedInvocations
      Namespace: AWS/Events
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: RuleName
          Value: !Ref RetailBatchScheduleRule
      TreatMissingData: notBreaching

  ReactiveSolicitationFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-reactive-solicitation-failures-${Environment}'
      AlarmDescription: 'Alert when reactive ceap rules fail to trigger'
      MetricName: FailedInvocations
      Namespace: AWS/Events
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: RuleName
          Value: !Ref CustomerOrderPlacedRule
      TreatMissingData: notBreaching

# ============================================================================
# Outputs
# ============================================================================

Outputs:
  EventBridgeRoleArn:
    Description: ARN of the EventBridge execution role
    Value: !GetAtt EventBridgeStepFunctionsRole.Arn
    Export:
      Name: !Sub '${ProjectName}-eventbridge-role-arn-${Environment}'

  RetailBatchScheduleRuleName:
    Description: Name of the retail batch schedule rule
    Value: !Ref RetailBatchScheduleRule
    Export:
      Name: !Sub '${ProjectName}-retail-batch-rule-${Environment}'

  SubscriptionBatchScheduleRuleName:
    Description: Name of the subscription batch schedule rule
    Value: !Ref SubscriptionBatchScheduleRule
    Export:
      Name: !Sub '${ProjectName}-subscription-batch-rule-${Environment}'

  CustomerOrderPlacedRuleName:
    Description: Name of the customer order placed rule
    Value: !Ref CustomerOrderPlacedRule
    Export:
      Name: !Sub '${ProjectName}-order-placed-rule-${Environment}'

  SubscriptionRenewalRuleName:
    Description: Name of the subscription renewal rule
    Value: !Ref SubscriptionRenewalRule
    Export:
      Name: !Sub '${ProjectName}-subscription-renewal-rule-${Environment}'
