AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda Function Configurations for General Solicitation Platform'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name for resource tagging and configuration

  ProjectName:
    Type: String
    Default: solicitation-platform
    Description: Project name for resource naming

Resources:
  # ============================================================================
  # IAM Roles for Lambda Functions
  # ============================================================================

  ETLLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-etl-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ETLLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # DynamoDB read/write permissions
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Candidates'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Candidates/index/*'
              # Athena query permissions
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                  - athena:StopQueryExecution
                Resource: '*'
              # S3 read permissions for data sources
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${ProjectName}-data-sources-${Environment}/*'
                  - !Sub 'arn:aws:s3:::${ProjectName}-data-sources-${Environment}'
              # S3 write permissions for Athena results
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - !Sub 'arn:aws:s3:::${ProjectName}-athena-results-${Environment}/*'
              # Glue permissions for data catalog
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetTable
                  - glue:GetPartitions
                Resource: '*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  FilterLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-filter-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: FilterLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # DynamoDB read permissions
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ProgramConfig'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ProgramConfig/index/*'
              # External service calls (for eligibility checks)
              - Effect: Allow
                Action:
                  - execute-api:Invoke
                Resource: '*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  ScoreLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-score-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ScoreLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # DynamoDB read/write permissions for score cache
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ScoreCache'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ScoreCache/index/*'
              # SageMaker endpoint invocation
              - Effect: Allow
                Action:
                  - sagemaker:InvokeEndpoint
                Resource: '*'
              # Feature store access
              - Effect: Allow
                Action:
                  - sagemaker:GetRecord
                  - sagemaker:BatchGetRecord
                Resource: '*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  StoreLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-store-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: StoreLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # DynamoDB batch write permissions
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Candidates'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Candidates/index/*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  ServeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-serve-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ServeLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # DynamoDB read permissions
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:BatchGetItem
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Candidates'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Candidates/index/*'
              # API Gateway integration
              - Effect: Allow
                Action:
                  - execute-api:Invoke
                Resource: '*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # ============================================================================
  # Lambda Functions
  # ============================================================================

  ETLLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-etl-${Environment}'
      Runtime: java17
      Handler: com.solicitation.workflow.ETLHandler::handleRequest
      Role: !GetAtt ETLLambdaRole.Arn
      MemorySize: 1024
      Timeout: 300
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          DATA_SOURCE_CONFIG: !Sub '${ProjectName}-data-sources-${Environment}'
          BATCH_SIZE: '1000'
          LOG_LEVEL: INFO
          CANDIDATES_TABLE: Candidates
          PROGRAM_CONFIG_TABLE: ProgramConfig
      Code:
        S3Bucket: !Sub '${ProjectName}-lambda-artifacts-${Environment}'
        S3Key: etl-lambda.jar
      Description: ETL Lambda function for extracting and transforming candidate data
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: ETL

  FilterLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-filter-${Environment}'
      Runtime: java17
      Handler: com.solicitation.workflow.FilterHandler::handleRequest
      Role: !GetAtt FilterLambdaRole.Arn
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          FILTER_CONFIG: !Sub '${ProjectName}-filter-config-${Environment}'
          LOG_LEVEL: INFO
          PROGRAM_CONFIG_TABLE: ProgramConfig
      Code:
        S3Bucket: !Sub '${ProjectName}-lambda-artifacts-${Environment}'
        S3Key: filter-lambda.jar
      Description: Filter Lambda function for applying eligibility and business rules
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: Filter

  ScoreLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-score-${Environment}'
      Runtime: java17
      Handler: com.solicitation.workflow.ScoreHandler::handleRequest
      Role: !GetAtt ScoreLambdaRole.Arn
      MemorySize: 1024
      Timeout: 120
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          MODEL_ENDPOINTS: !Sub '${ProjectName}-model-endpoints-${Environment}'
          FEATURE_STORE_CONFIG: !Sub '${ProjectName}-feature-store-${Environment}'
          LOG_LEVEL: INFO
          SCORE_CACHE_TABLE: ScoreCache
          CACHE_TTL_HOURS: '24'
      Code:
        S3Bucket: !Sub '${ProjectName}-lambda-artifacts-${Environment}'
        S3Key: score-lambda.jar
      Description: Score Lambda function for executing scoring models
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: Score

  StoreLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-store-${Environment}'
      Runtime: java17
      Handler: com.solicitation.workflow.StoreHandler::handleRequest
      Role: !GetAtt StoreLambdaRole.Arn
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          BATCH_SIZE: '25'
          LOG_LEVEL: INFO
          CANDIDATES_TABLE: Candidates
      Code:
        S3Bucket: !Sub '${ProjectName}-lambda-artifacts-${Environment}'
        S3Key: store-lambda.jar
      Description: Store Lambda function for batch writing candidates to DynamoDB
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: Store

  ServeLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-serve-${Environment}'
      Runtime: java17
      Handler: com.solicitation.serving.ServeHandler::handleRequest
      Role: !GetAtt ServeLambdaRole.Arn
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          CACHE_CONFIG: !Sub '${ProjectName}-cache-config-${Environment}'
          LOG_LEVEL: INFO
          CANDIDATES_TABLE: Candidates
          MAX_RESULTS_PER_QUERY: '100'
      Code:
        S3Bucket: !Sub '${ProjectName}-lambda-artifacts-${Environment}'
        S3Key: serve-lambda.jar
      Description: Serve Lambda function for low-latency candidate retrieval API
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: Serve

  # ============================================================================
  # CloudWatch Log Groups
  # ============================================================================

  ETLLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-etl-${Environment}'
      RetentionInDays: 30

  FilterLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-filter-${Environment}'
      RetentionInDays: 30

  ScoreLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-score-${Environment}'
      RetentionInDays: 30

  StoreLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-store-${Environment}'
      RetentionInDays: 30

  ServeLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-serve-${Environment}'
      RetentionInDays: 30

# ============================================================================
# Outputs
# ============================================================================

Outputs:
  ETLLambdaArn:
    Description: ARN of the ETL Lambda function
    Value: !GetAtt ETLLambdaFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-etl-lambda-arn-${Environment}'

  FilterLambdaArn:
    Description: ARN of the Filter Lambda function
    Value: !GetAtt FilterLambdaFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-filter-lambda-arn-${Environment}'

  ScoreLambdaArn:
    Description: ARN of the Score Lambda function
    Value: !GetAtt ScoreLambdaFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-score-lambda-arn-${Environment}'

  StoreLambdaArn:
    Description: ARN of the Store Lambda function
    Value: !GetAtt StoreLambdaFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-store-lambda-arn-${Environment}'

  ServeLambdaArn:
    Description: ARN of the Serve Lambda function
    Value: !GetAtt ServeLambdaFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-serve-lambda-arn-${Environment}'

  ETLLambdaRoleArn:
    Description: ARN of the ETL Lambda IAM role
    Value: !GetAtt ETLLambdaRole.Arn
    Export:
      Name: !Sub '${ProjectName}-etl-lambda-role-arn-${Environment}'

  FilterLambdaRoleArn:
    Description: ARN of the Filter Lambda IAM role
    Value: !GetAtt FilterLambdaRole.Arn
    Export:
      Name: !Sub '${ProjectName}-filter-lambda-role-arn-${Environment}'

  ScoreLambdaRoleArn:
    Description: ARN of the Score Lambda IAM role
    Value: !GetAtt ScoreLambdaRole.Arn
    Export:
      Name: !Sub '${ProjectName}-score-lambda-role-arn-${Environment}'

  StoreLambdaRoleArn:
    Description: ARN of the Store Lambda IAM role
    Value: !GetAtt StoreLambdaRole.Arn
    Export:
      Name: !Sub '${ProjectName}-store-lambda-role-arn-${Environment}'

  ServeLambdaRoleArn:
    Description: ARN of the Serve Lambda IAM role
    Value: !GetAtt ServeLambdaRole.Arn
    Export:
      Name: !Sub '${ProjectName}-serve-lambda-role-arn-${Environment}'
